version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - kittygram_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 kittygram_backend.wsgi:application
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ../tests:/app/tests
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - kittygram_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - static_volume:/app/build
    depends_on:
      - backend
    networks:
      - kittygram_network

 nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/app/build
      - media_volume:/app/media
    ports:
      - 7779:80
    depends_on:
      - backend
      - frontend
    networks:
      - kittygram_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
      - kittygram_network
          driver: bridge

