version: '3.9'

services:
  web:
    image: your-django-app-image:latest
    command: gunicorn kittygram_backend.wsgi:application --bind 0.0.0.0:9000
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file: .env.production
    ports:
      - "9000:9000"
    depends_on:
      - db

  db:
    image: postgres:13.10
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static_volume:/var/www/html/static
      - media_volume:/var/www/html/media
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
