services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: miura193/kittygram_backend
    command: gunicorn --bind 0.0.0.0:8000 kittygram_backend.wsgi:application
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    image: miura193/kittygram_frontend
    volumes:
      - static_volume:/app/static
    depends_on:
      - backend

  nginx:
    image: miura193/kittygram_gateway
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - 7779:80
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  static_volume:
  media_volume:

