name: Main kittygram_final workflow

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8==6.0.0 flake8-isort==6.0.0
          pip install -r ./backend/requirements.txt

      - name: Lint code
        run: |
          flake8 backend/ --max-line-length=79

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: kittygram
          POSTGRES_USER: kittygram_user
          POSTGRES_PASSWORD: yourpassword
          POSTGRES_HOST: localhost
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U $POSTGRES_USER" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5
        volumes:
          - postgres_data:/var/lib/postgresql/data
    env:
      POSTGRES_DB: kittygram
      POSTGRES_USER: kittygram_user
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_HOST: localhost
      DJANGO_SECRET_KEY: your_secret_key

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies for backend
        run: |
          cd backend
          pip install --upgrade pip
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic --noinput

      - name: Run backend tests
        run: |
          cd backend
          python manage.py test

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies for frontend
        run: |
          cd frontend
          npm install

      - name: Run frontend tests
        run: |
          cd frontend
          npm test

  build_and_push:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/kittygram_backend ./backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/kittygram_backend

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/kittygram_frontend ./frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/kittygram_frontend

      - name: Build and push gateway image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/kittygram_gateway ./nginx
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/kittygram_gateway

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Deploy to server
        run: |
          ssh user@your_server_ip 'cd /path_to_your_project && docker-compose pull && docker-compose up -d'

      - name: Run database migrations and collect static files
        run: |
          ssh user@your_server_ip 'docker-compose exec backend python manage.py migrate'
          ssh user@your_server_ip 'docker-compose exec backend python manage.py collectstatic --noinput'
          
      - name: Notify on Telegram
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="Kittygram deployment completed successfully"
